"""Step 2 of the one-off data extraction: writes src/data/*.ts and image assets.
Usage: python3 scripts/extract.py web.json   (needs Pillow and Playwright for sign rasterising)"""
import json, sys, os, re, base64, io
from PIL import Image
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
d = json.load(open(sys.argv[1]))
os.makedirs(f'{ROOT}/src/data', exist_ok=True)
os.makedirs(f'{ROOT}/assets/questions', exist_ok=True)
os.makedirs(f'{ROOT}/assets/signs', exist_ok=True)
HDR = '// Generated by scripts/extract.py from the web app. Do not edit by hand.\n'
def js(o): return json.dumps(o, ensure_ascii=False, indent=1)
def w(name, body): open(f'{ROOT}/src/data/{name}', 'w', encoding='utf8').write(HDR + body)

# ---------- question images: base64 -> webp files ----------
from_web = {}
for k, uri in d['IMG'].items():
    m = re.match(r'data:image/(\w+);base64,(.*)', uri, re.S)
    im = Image.open(io.BytesIO(base64.b64decode(m.group(2))))
    im = im.convert('RGBA') if im.mode in ('P', 'LA', 'RGBA') else im.convert('RGB')
    im.save(f'{ROOT}/assets/questions/{k}.webp', 'WEBP', quality=88, method=6)
    from_web[k] = im.size
w('questionImages.ts', 'import type { ImageSourcePropType } from \'react-native\';\n\nexport const QUESTION_IMAGES: Record<string, ImageSourcePropType> = {\n' +
  ''.join(f"  '{k}': require('../../assets/questions/{k}.webp'),\n" for k in sorted(from_web)) + '};\n')

# ---------- signs ----------
signs = [{'id': f's{i:03d}', 'group': s['g'], 'nameAr': s['a'], 'nameEn': s['e']} for i, s in enumerate(d['SA'])]
w('signs.ts', "import type { Sign } from './types';\n\nexport const SIGN_GROUPS = " + js(d['GR']) + " as const;\n\nexport const SIGNS: Sign[] = " + js(signs) + ';\n')
w('signImages.ts', 'import type { ImageSourcePropType } from \'react-native\';\n\nexport const SIGN_IMAGES: Record<string, ImageSourcePropType> = {\n' +
  ''.join(f"  '{s['id']}': require('../../assets/signs/{s['id']}.webp'),\n" for s in signs) + '};\n')
json.dump([{'id': f's{i:03d}', 'svg': s['s']} for i, s in enumerate(d['SA'])], open('/tmp/claude-0/signs_svg.json', 'w'))

# ---------- questions ----------
LOCK = re.compile(r'(جميع|كل ما|كلا|كلتا|لا شيء|لا شئ|أعلاه|اعلاه|ما سبق|الاجابتين|الإجابتين)')
def ref(key):
    return {'kind': 'sign', 'id': f's{int(key[3:]):03d}'} if key.startswith('sa:') else {'kind': 'photo', 'key': key}
qs = []
for i, (q, opts, c, _sg, im) in enumerate(d['Q']):
    options = []
    for j, t in enumerate(opts):
        oid = 'abcd'[j]
        options.append({'id': oid, 'image': ref(t[1:])} if t.startswith('@') else {'id': oid, 'text': t.strip()})
    item = {'id': f'q{i:03d}', 'question': q.strip(), 'options': options, 'correctAnswerId': 'abcd'[c]}
    if im: item['image'] = ref(im)
    if any(LOCK.search(t) for t in opts): item['lockOrder'] = True
    kinds = [im] + [t[1:] for t in opts if t.startswith('@')]
    item['category'] = 'signs' if any(k and k.startswith('sa:') for k in kinds) else 'pictures' if any(kinds) else 'general'
    qs.append(item)
w('questions.ts', "import type { Question } from './types';\n\nexport const QUESTIONS: Question[] = " + js(qs) + ';\n')
json.dump(d['ORDER'], open(f'{ROOT}/src/features/levels/__fixtures__/webOrder.json', 'w')) if os.path.isdir(f'{ROOT}/src/features/levels/__fixtures__') else None

# ---------- guide content ----------
book = [{'id': f't{i:02d}', 'icon': t['ic'], 'title': t['t'], 'blocks': [({'table': r} if isinstance(r, list) else {'text': r}) for r in t['r']]} for i, t in enumerate(d['BOOK'])]
w('licenseGuide.ts', "import type { GuideTopic } from './types';\n\n/** From the official trainee guide (دليل المتدرب). Arabic only. */\nexport const GUIDE_SOURCE = 'official' as const;\n\nexport const GUIDE_TOPICS: GuideTopic[] = " + js(book) + ';\n')
tips = {'ar': d['GUIDE'], 'en': d['GUIDE_L']['en'], 'ur': d['GUIDE_L']['ur']}
tips = {l: [{'title': t, 'lines': ls} for t, ls in v] for l, v in tips.items()}
w('tips.ts', "import type { Lang, Tip } from './types';\n\n/** Quick tips summarised from the official trainee guide. */\nexport const TIPS: Record<Lang, Tip[]> = " + js(tips) + ';\n\nexport const TIRE_RATINGS: [string, number][] = ' + json.dumps(d['TIRES']) + ';\n')
steps = {'ar': d['STEPS'], 'en': d['I18N']['en']['steps'], 'ur': d['I18N']['ur']['steps']}
steps = {l: [{'title': t, 'body': b} for t, b in v] for l, v in steps.items()}
w('steps.ts', "import type { Lang, Step } from './types';\n\n/** Compiled from public service pages (general information, not official). Verify on Absher. */\nexport const STEPS_SOURCE = 'general' as const;\n\nexport const STEPS: Record<Lang, Step[]> = " + js(steps) + ';\n')

# ---------- schools & cities ----------
schools = [{'id': f'sch{i:02d}', 'name': n, 'cities': cs, 'description': desc} for i, (n, cs, desc) in enumerate(d['SCH'])]
w('schools.ts', "import type { School } from './types';\n\n/** Compiled from public sources (Absher's own list requires login). Verify on Absher. */\nexport const SCHOOLS_SOURCE = 'general' as const;\nexport const SCHOOLS_CHECKED = '2026-10-02';\n\nexport const SCHOOLS: School[] = " + js(schools) + ';\n')
cities = [{'name': n, 'region': v[0], 'lat': v[1], 'lng': v[2]} for n, v in d['CITY'].items()]
w('cities.ts', "import type { City } from './types';\n\n/** Approximate city-centre coordinates. */\nexport const CITIES: City[] = " + js(cities) + ';\n')

# ---------- icons ----------
w('iconPaths.ts', '/** Thin-line icon set from the web app (24x24 SVG markup). */\nexport const ICON_PATHS = ' + js(d['P']) + ' as const;\n\nexport type IconName = keyof typeof ICON_PATHS;\n')

# ---------- web strings (for i18n) ----------
def conv(v):
    if isinstance(v, str) and v.startswith('__FN__'):
        return {'__fn': v[6:]}
    return v
json.dump({l: {k: conv(v) for k, v in d['I18N'][l].items()} for l in d['I18N']}, open('/tmp/claude-0/i18n_web.json', 'w'), ensure_ascii=False, indent=1)
json.dump(d['GT'], open('/tmp/claude-0/gt_web.json', 'w'), ensure_ascii=False, indent=1)
print('questions', len(qs), 'images', len(from_web), 'signs', len(signs), 'topics', len(book), 'schools', len(schools), 'cities', len(cities))
