#!/usr/bin/env python3
"""
Builds src/data/nastaliqIndent.ts: for each Urdu word in the app whose first letter draws past the start of its line
in Noto Nastaliq Urdu, the number of no-break spaces to put before it when it starts a line.

Android clips text at the padding edge of its TextView, so ink past the line start (the right edge in RTL) is lost:
an initial ک's slanted stroke reaches 0.44 em out and "کیٹیگری" drew as "لیٹیگری" (QA build 33). The overhang is
measured by shaping each word with HarfBuzz in both weights the app uses and comparing the ink's right edge with the
word's advance. Words that overhang by less than THRESHOLD em are left out.

Run after the Urdu text changes:  pip install uharfbuzz && python3 scripts/nastaliq-indent.py
"""
import json
import math
import os
import re

import uharfbuzz as hb

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS = [
    f'node_modules/@expo-google-fonts/noto-nastaliq-urdu/{w}/NotoNastaliqUrdu_{w}.ttf' for w in ('400Regular', '600SemiBold')
]
SOURCES = [
    'src/i18n/ur.ts',
    'src/data/i18n/questions/ur.ts',
    'src/data/i18n/guide/ur.ts',
    'src/data/i18n/signs.ts',
    'src/data/i18n/places.ts',
    'src/data/tips.ts',
    'src/data/steps.ts',
]
THRESHOLD = 0.05  # em; smaller overhangs are not visible
FALLBACK_LETTERS = '\u06a9\u06af'  # ک گ: indented by default in the app when a word was not measured
URDU = re.compile('[؀-ۿݐ-ݿ]')
# Same trimming as wordKey() in src/components/learn/table.ts.
TRAIL = re.compile('[،۔؟؛!:,.)»"\'‏⁩]+$')
LEAD = re.compile('^[ ​-‏⁠⁦-⁩]+')


def overhang(font, upem, word):
    buf = hb.Buffer()
    buf.add_str(word)
    buf.guess_segment_properties()
    hb.shape(font, buf)
    x = 0
    ink = -1e9
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        e = font.get_glyph_extents(info.codepoint)
        if e and e.width:
            ink = max(ink, x + pos.x_offset + e.x_bearing + e.width)
        x += pos.x_advance
    return (ink - x) / upem


def main():
    fonts = []
    for path in FONTS:
        face = hb.Face(hb.Blob.from_file_path(os.path.join(ROOT, path)))
        fonts.append((hb.Font(face), face.upem))
    nbsp = min(f.get_nominal_glyph(0xA0) and f.get_glyph_h_advance(f.get_nominal_glyph(0xA0)) / u for f, u in fonts)
    words = set()
    for src in SOURCES:
        with open(os.path.join(ROOT, src), encoding='utf-8') as fh:
            # String literals first ('…', "…", `…`), then words split as the app's T splits them (on ' ').
            for literal in re.findall(r"'((?:[^'\\\n]|\\.)*)'|\"((?:[^\"\\\n]|\\.)*)\"|`([^`]*)`", fh.read()):
                text = ''.join(literal)  # findall gives '' for the quote kinds that did not match
                text = text.replace('\\n', ' ').replace('\\"', '"').replace("\\'", "'")  # undo escapes
                for token in text.split(' '):
                    token = TRAIL.sub('', LEAD.sub('', token))
                    if token and URDU.match(token):
                        words.add(token)
    table = {}
    for word in sorted(words):
        em = max(overhang(f, u, word) for f, u in fonts)
        if em >= THRESHOLD:
            table[word] = math.ceil(em / nbsp)
        elif word[0] in FALLBACK_LETTERS:
            # Measured and fine: recorded so the app's fallback for unmeasured ک / گ words leaves it alone ("کے").
            table[word] = 0
    out = os.path.join(ROOT, 'src/data/nastaliqIndent.ts')
    with open(out, 'w', encoding='utf-8') as fh:
        fh.write('// Generated by scripts/nastaliq-indent.py from the Urdu text and the Noto Nastaliq Urdu fonts. Do not edit.\n')
        fh.write('// Word -> no-break spaces to put before it when it starts a line (its first letter draws past the line start).\n')
        fh.write(f'export const NBSP_EM = {nbsp:.3f};\n')
        fh.write('export const NASTALIQ_INDENT: Record<string, number> = ')
        fh.write(json.dumps(table, ensure_ascii=False, separators=(',', ':'), sort_keys=True))
        fh.write(';\n')
    print(f'{len(words)} words, {len(table)} need an indent, NBSP {nbsp:.3f} em -> {out}')


if __name__ == '__main__':
    main()
