// Splits the combined translation tables into one module per language, so the app only evaluates the
// language the reader picked (see src/data/localize.ts). Run after regenerating scripts/generated/{questions,guide}.ts:
//   node scripts/split-i18n.js
const fs = require('fs');
const path = require('path');
const LANGS = ['en', 'ur', 'hi', 'bn'];
const dir = path.join(__dirname, '..', 'src', 'data', 'i18n');
const combined = path.join(__dirname, 'generated'); // all-language tables built from scripts/translations*/

function readTable(file, name) {
  const src = fs.readFileSync(path.join(combined, file), 'utf8');
  const start = src.indexOf(`export const ${name}`);
  const json = src.slice(src.indexOf('= ', start) + 2).trim().replace(/;$/, '');
  return JSON.parse(json);
}

function write(sub, typeImport, typeName, table) {
  fs.mkdirSync(path.join(dir, sub), { recursive: true });
  for (const lang of LANGS) {
    const out = {};
    for (const [id, byLang] of Object.entries(table)) if (byLang[lang]) out[id] = byLang[lang];
    const body = `// Generated by scripts/split-i18n.js. Do not edit by hand.\n${typeImport}\nconst table: Record<string, ${typeName}> = ${JSON.stringify(out)};\nexport default table;\n`;
    fs.writeFileSync(path.join(dir, sub, `${lang}.ts`), body);
  }
}

const q = readTable('questions.ts', 'QUESTION_TEXT');
write('questions', "import type { QText } from '../types';", 'QText', q);
const g = readTable('guide.ts', 'GUIDE_TEXT');
write('guide', "import type { TopicText } from '../types';", 'TopicText', g);
console.log(`questions: ${Object.keys(q).length}, guide topics: ${Object.keys(g).length}`);
