// Generated by scripts/extract.py from the web app. Do not edit by hand.
import type { City } from './types';

/** Approximate city-centre coordinates. */
export const CITIES: City[] = [
 {
  "name": "الرياض",
  "region": "الرياض",
  "lat": 24.71,
  "lng": 46.68
 },
 {
  "name": "الخرج",
  "region": "الرياض",
  "lat": 24.15,
  "lng": 47.31
 },
 {
  "name": "الدوادمي",
  "region": "الرياض",
  "lat": 24.51,
  "lng": 44.39
 },
 {
  "name": "المجمعة",
  "region": "الرياض",
  "lat": 25.9,
  "lng": 45.35
 },
 {
  "name": "شقراء",
  "region": "الرياض",
  "lat": 25.25,
  "lng": 45.25
 },
 {
  "name": "وادي الدواسر",
  "region": "الرياض",
  "lat": 20.47,
  "lng": 44.79
 },
 {
  "name": "جدة",
  "region": "مكة المكرمة",
  "lat": 21.54,
  "lng": 39.17
 },
 {
  "name": "مكة المكرمة",
  "region": "مكة المكرمة",
  "lat": 21.42,
  "lng": 39.83
 },
 {
  "name": "الطائف",
  "region": "مكة المكرمة",
  "lat": 21.27,
  "lng": 40.42
 },
 {
  "name": "المدينة المنورة",
  "region": "المدينة المنورة",
  "lat": 24.47,
  "lng": 39.61
 },
 {
  "name": "الدمام",
  "region": "الشرقية",
  "lat": 26.43,
  "lng": 50.1
 },
 {
  "name": "الظهران",
  "region": "الشرقية",
  "lat": 26.29,
  "lng": 50.11
 },
 {
  "name": "الخبر",
  "region": "الشرقية",
  "lat": 26.28,
  "lng": 50.21
 },
 {
  "name": "جازان",
  "region": "جازان",
  "lat": 16.89,
  "lng": 42.55
 },
 {
  "name": "أبها",
  "region": "عسير",
  "lat": 18.22,
  "lng": 42.51
 },
 {
  "name": "حائل",
  "region": "حائل",
  "lat": 27.52,
  "lng": 41.7
 },
 {
  "name": "نجران",
  "region": "نجران",
  "lat": 17.49,
  "lng": 44.13
 },
 {
  "name": "سكاكا",
  "region": "الجوف",
  "lat": 29.97,
  "lng": 40.21
 },
 {
  "name": "عرعر",
  "region": "الحدود الشمالية",
  "lat": 30.98,
  "lng": 41.02
 },
 {
  "name": "تبوك",
  "region": "تبوك",
  "lat": 28.38,
  "lng": 36.57
 },
 {
  "name": "الباحة",
  "region": "الباحة",
  "lat": 20.01,
  "lng": 41.47
 },
 {
  "name": "المخواة",
  "region": "الباحة",
  "lat": 19.79,
  "lng": 41.43
 },
 {
  "name": "القطيف",
  "region": "الشرقية",
  "lat": 26.56,
  "lng": 50.01
 },
 {
  "name": "الجبيل",
  "region": "الشرقية",
  "lat": 27.01,
  "lng": 49.66
 },
 {
  "name": "الأحساء",
  "region": "الشرقية",
  "lat": 25.38,
  "lng": 49.59
 },
 {
  "name": "حفر الباطن",
  "region": "الشرقية",
  "lat": 28.43,
  "lng": 45.96
 },
 {
  "name": "ينبع",
  "region": "المدينة المنورة",
  "lat": 24.09,
  "lng": 38.06
 },
 {
  "name": "بريدة",
  "region": "القصيم",
  "lat": 26.33,
  "lng": 43.97
 },
 {
  "name": "عنيزة",
  "region": "القصيم",
  "lat": 26.08,
  "lng": 43.99
 },
 {
  "name": "الرس",
  "region": "القصيم",
  "lat": 25.87,
  "lng": 43.5
 }
];
