// Generated by scripts/extract.py from the web app. Do not edit by hand.
/** Thin-line icon set from the web app (24x24 SVG markup). */
export const ICON_PATHS = {
 "book": "<path d=\"M4 19V5a2 2 0 0 1 2-2h14v16H6a2 2 0 0 0-2 2 2 2 0 0 0 2 2h14\"/><path d=\"M9 8h7\"/>",
 "signs": "<path d=\"M12 3 2.5 20h19L12 3z\"/><path d=\"M12 10v4M12 17.2v.1\"/>",
 "license": "<rect x=\"3\" y=\"5\" width=\"18\" height=\"14\" rx=\"2.5\"/><circle cx=\"9\" cy=\"11\" r=\"2\"/><path d=\"M6 16c.6-1.4 1.8-2 3-2s2.4.6 3 2M14.5 10h4M14.5 13.5h3\"/>",
 "schools": "<path d=\"M12 21s7-6.2 7-11.5A7 7 0 0 0 5 9.5C5 14.8 12 21 12 21z\"/><circle cx=\"12\" cy=\"9.5\" r=\"2.5\"/>",
 "exam": "<rect x=\"5\" y=\"4\" width=\"14\" height=\"17\" rx=\"2.5\"/><path d=\"M9 4V3h6v1M8.5 13l2.2 2.2L15.5 10\"/>",
 "go": "<path d=\"M15 6l-6 6 6 6\"/>",
 "speed": "<path d=\"M4 16a8 8 0 1 1 16 0\"/><path d=\"M12 16l4-5\"/>",
 "aid": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"5\"/><path d=\"M12 8v8M8 12h8\"/>",
 "fine": "<rect x=\"3\" y=\"6\" width=\"18\" height=\"12\" rx=\"2.5\"/><circle cx=\"12\" cy=\"12\" r=\"2.5\"/><path d=\"M6.5 9.5v.1M17.5 14.5v.1\"/>",
 "pts": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M12 7.5v5M12 16v.1\"/>",
 "road": "<path d=\"M8 3 4 21M16 3l4 18M12 4v3M12 11v3M12 18v3\"/>",
 "users": "<circle cx=\"9\" cy=\"8\" r=\"3\"/><path d=\"M3.5 20c.6-3.4 2.9-5 5.5-5s4.9 1.6 5.5 5\"/><circle cx=\"17\" cy=\"9\" r=\"2.3\"/><path d=\"M16.5 14.2c2.3.2 3.7 1.6 4.2 4\"/>",
 "duty": "<path d=\"M9 6h11M9 12h11M9 18h11\"/><path d=\"M4 6l1 1 2-2M4 12l1 1 2-2M4 18l1 1 2-2\"/>",
 "car": "<path d=\"M5 16v-5l2-5h10l2 5v5M3 16h18M7.5 19v-3M16.5 19v-3M5 11h14\"/>",
 "lane": "<path d=\"M4 8h16M16 4l4 4-4 4M20 16H4M8 12l-4 4 4 4\"/>",
 "loop": "<path d=\"M20 12a8 8 0 1 1-3-6.2\"/><path d=\"M20 4v4h-4\"/>",
 "light": "<rect x=\"8\" y=\"2.5\" width=\"8\" height=\"19\" rx=\"3\"/><circle cx=\"12\" cy=\"7.5\" r=\"1.2\"/><circle cx=\"12\" cy=\"12\" r=\"1.2\"/><circle cx=\"12\" cy=\"16.5\" r=\"1.2\"/>",
 "fork": "<path d=\"M12 21V11M12 11 6 4M12 11l6-7\"/>",
 "rail": "<path d=\"M7 3l-3 18M17 3l3 18M5.5 9h13M4.8 15h14.4\"/>",
 "gap": "<path d=\"M3 12h18M7 8l-4 4 4 4M17 8l4 4-4 4\"/>",
 "home": "<path d=\"M3 11.5 12 4l9 7.5M5.5 10v10h4.5v-6h4v6h4.5V10\"/>",
 "globe": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M3 12h18M12 3c2.6 2.6 4 5.8 4 9s-1.4 6.4-4 9c-2.6-2.6-4-5.8-4-9s1.4-6.4 4-9z\"/>",
 "check": "<path d=\"M5 12.5l4.5 4.5L19 7.5\"/>",
 "clock": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M12 7v5l3 2\"/>",
 "sun": "<circle cx=\"12\" cy=\"12\" r=\"4\"/><path d=\"M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4\"/>",
 "moon": "<path d=\"M20 14.5A8 8 0 0 1 9.5 4 8 8 0 1 0 20 14.5z\"/>",
 "bolt": "<path d=\"M13 2 4 14h6l-1 8 9-12h-6l1-8z\"/>",
 "flame": "<path d=\"M12 22c4 0 7-2.8 7-7 0-3.5-2-5.8-3.5-7.5-.4 1.6-1.4 2.6-2.5 3 0-3-1.2-5.6-3.5-7.5C9 6 5 9 5 15c0 4.2 3 7 7 7z\"/>",
 "heart": "<path d=\"M12 21s-8-5.2-8-11a4.5 4.5 0 0 1 8-2.8A4.5 4.5 0 0 1 20 10c0 5.8-8 11-8 11z\"/>",
 "lock": "<rect x=\"5\" y=\"11\" width=\"14\" height=\"10\" rx=\"2.5\"/><path d=\"M8 11V8a4 4 0 0 1 8 0v3\"/>",
 "close": "<path d=\"M6 6l12 12M18 6 6 18\"/>",
 "flag": "<path d=\"M5 21V4M5 4h11l-2 4 2 4H5\"/>",
 "up": "<path d=\"M12 19V5M6 11l6-6 6 6\"/>"
} as const;

export type IconName = keyof typeof ICON_PATHS;
