// Generated by scripts/extract.py from the web app. Do not edit by hand.
import type { Sign } from './types';

export const SIGN_GROUPS = [
 "تحذيرية",
 "أولوية",
 "ممنوعات",
 "إلزامية",
 "إرشادية",
 "لوحات الطرق"
] as const;

export const SIGNS: Sign[] = [
 {
  "id": "s000",
  "group": "تحذيرية",
  "nameAr": "منعطف لليسار",
  "nameEn": "Curve to left"
 },
 {
  "id": "s001",
  "group": "تحذيرية",
  "nameAr": "منعطف لليمين",
  "nameEn": "Curve to right"
 },
 {
  "id": "s002",
  "group": "تحذيرية",
  "nameAr": "منعطف حاد لليسار",
  "nameEn": "Sharp curve to left"
 },
 {
  "id": "s003",
  "group": "تحذيرية",
  "nameAr": "منعطف حاد لليمين",
  "nameEn": "Sharp curve to right"
 },
 {
  "id": "s004",
  "group": "تحذيرية",
  "nameAr": "منعطفات أولها لليمين",
  "nameEn": "Curves — first to the right"
 },
 {
  "id": "s005",
  "group": "تحذيرية",
  "nameAr": "منعطفات أولها لليسار",
  "nameEn": "Curves — first to the left"
 },
 {
  "id": "s006",
  "group": "تحذيرية",
  "nameAr": "منعطف معكوس لليسار",
  "nameEn": "Reverse curve to left"
 },
 {
  "id": "s007",
  "group": "تحذيرية",
  "nameAr": "منعطف معكوس لليمين",
  "nameEn": "Reverse curve to right"
 },
 {
  "id": "s008",
  "group": "تحذيرية",
  "nameAr": "منحدر شديد",
  "nameEn": "Steep descent"
 },
 {
  "id": "s009",
  "group": "تحذيرية",
  "nameAr": "صعود شديد",
  "nameEn": "Steep ascent"
 },
 {
  "id": "s010",
  "group": "تحذيرية",
  "nameAr": "الطريق يضيق من الجانبين",
  "nameEn": "Road narrows on both sides"
 },
 {
  "id": "s011",
  "group": "تحذيرية",
  "nameAr": "الطريق يضيق من اليسار",
  "nameEn": "Road narrows on the left"
 },
 {
  "id": "s012",
  "group": "تحذيرية",
  "nameAr": "الطريق يضيق من اليمين",
  "nameEn": "Road narrows on the right"
 },
 {
  "id": "s013",
  "group": "تحذيرية",
  "nameAr": "رصيف أو ضفة غير محمية",
  "nameEn": "Unprotected quayside or riverbank"
 },
 {
  "id": "s014",
  "group": "تحذيرية",
  "nameAr": "طريق غير مستوٍ",
  "nameEn": "Uneven road"
 },
 {
  "id": "s015",
  "group": "تحذيرية",
  "nameAr": "مطب صناعي",
  "nameEn": "Speed bump"
 },
 {
  "id": "s016",
  "group": "تحذيرية",
  "nameAr": "منخفض في الطريق",
  "nameEn": "Dip"
 },
 {
  "id": "s017",
  "group": "تحذيرية",
  "nameAr": "سطح زلق",
  "nameEn": "Slippery surface"
 },
 {
  "id": "s018",
  "group": "تحذيرية",
  "nameAr": "حصى متناثر",
  "nameEn": "Loose gravel"
 },
 {
  "id": "s019",
  "group": "تحذيرية",
  "nameAr": "سقوط صخور",
  "nameEn": "Falling rocks"
 },
 {
  "id": "s020",
  "group": "تحذيرية",
  "nameAr": "معبر مشاة أمامك",
  "nameEn": "Pedestrian crossing ahead"
 },
 {
  "id": "s021",
  "group": "تحذيرية",
  "nameAr": "معبر مدرسة",
  "nameEn": "School crossing"
 },
 {
  "id": "s022",
  "group": "تحذيرية",
  "nameAr": "دراجات هوائية",
  "nameEn": "Cyclists"
 },
 {
  "id": "s023",
  "group": "تحذيرية",
  "nameAr": "عبور جمال",
  "nameEn": "Camel crossing"
 },
 {
  "id": "s024",
  "group": "تحذيرية",
  "nameAr": "عبور حيوانات",
  "nameEn": "Animal crossing"
 },
 {
  "id": "s025",
  "group": "تحذيرية",
  "nameAr": "إشارات ضوئية أمامك (عمودية)",
  "nameEn": "Traffic lights ahead (vertical)"
 },
 {
  "id": "s026",
  "group": "تحذيرية",
  "nameAr": "إشارات ضوئية أمامك (أفقية)",
  "nameEn": "Traffic lights ahead (horizontal)"
 },
 {
  "id": "s027",
  "group": "تحذيرية",
  "nameAr": "طائرات على ارتفاع منخفض",
  "nameEn": "Low-flying aircraft"
 },
 {
  "id": "s028",
  "group": "تحذيرية",
  "nameAr": "رياح جانبية",
  "nameEn": "Crosswinds"
 },
 {
  "id": "s029",
  "group": "تحذيرية",
  "nameAr": "طريق باتجاهين",
  "nameEn": "Two-way traffic"
 },
 {
  "id": "s030",
  "group": "تحذيرية",
  "nameAr": "تقاطع طرق",
  "nameEn": "Crossroads"
 },
 {
  "id": "s031",
  "group": "تحذيرية",
  "nameAr": "طريق فرعي من اليسار",
  "nameEn": "Side road to the left"
 },
 {
  "id": "s032",
  "group": "تحذيرية",
  "nameAr": "طريق فرعي من اليمين",
  "nameEn": "Side road to the right"
 },
 {
  "id": "s033",
  "group": "تحذيرية",
  "nameAr": "إشارة قف أمامك",
  "nameEn": "Stop sign ahead"
 },
 {
  "id": "s034",
  "group": "تحذيرية",
  "nameAr": "إشارة أعطِ الأولوية أمامك",
  "nameEn": "Give way sign ahead"
 },
 {
  "id": "s035",
  "group": "تحذيرية",
  "nameAr": "دوار أمامك",
  "nameEn": "Roundabout ahead"
 },
 {
  "id": "s036",
  "group": "تحذيرية",
  "nameAr": "أكتاف رخوة",
  "nameEn": "Soft verges"
 },
 {
  "id": "s037",
  "group": "تحذيرية",
  "nameAr": "جسر بمسار واحد",
  "nameEn": "One-lane bridge"
 },
 {
  "id": "s038",
  "group": "تحذيرية",
  "nameAr": "جسر ضيق",
  "nameEn": "Narrow bridge"
 },
 {
  "id": "s039",
  "group": "تحذيرية",
  "nameAr": "نفق",
  "nameEn": "Tunnel"
 },
 {
  "id": "s040",
  "group": "تحذيرية",
  "nameAr": "سلسلة مطبات",
  "nameEn": "Series of speed bumps"
 },
 {
  "id": "s041",
  "group": "تحذيرية",
  "nameAr": "بداية طريق مزدوج",
  "nameEn": "Start of dual carriageway"
 },
 {
  "id": "s042",
  "group": "تحذيرية",
  "nameAr": "نهاية طريق مزدوج",
  "nameEn": "End of dual carriageway"
 },
 {
  "id": "s043",
  "group": "تحذيرية",
  "nameAr": "اندماج مع حركة المرور من اليمين",
  "nameEn": "Merging with traffic on right"
 },
 {
  "id": "s044",
  "group": "تحذيرية",
  "nameAr": "اندماج حركة المرور من اليمين",
  "nameEn": "Traffic merges from right"
 },
 {
  "id": "s045",
  "group": "تحذيرية",
  "nameAr": "تحديد ارتفاع أمامك",
  "nameEn": "Height restriction ahead"
 },
 {
  "id": "s046",
  "group": "تحذيرية",
  "nameAr": "مركز إطفاء",
  "nameEn": "Fire station"
 },
 {
  "id": "s047",
  "group": "تحذيرية",
  "nameAr": "أخطار أخرى",
  "nameEn": "Other dangers"
 },
 {
  "id": "s048",
  "group": "تحذيرية",
  "nameAr": "كثبان رملية",
  "nameEn": "Sand dunes"
 },
 {
  "id": "s049",
  "group": "تحذيرية",
  "nameAr": "عبور مياه",
  "nameEn": "Water crossing"
 },
 {
  "id": "s050",
  "group": "تحذيرية",
  "nameAr": "كابل كهرباء علوي أمامك",
  "nameEn": "Electrified overhead cable ahead"
 },
 {
  "id": "s051",
  "group": "تحذيرية",
  "nameAr": "إشارات ضوئية أمامك",
  "nameEn": "Traffic lights ahead"
 },
 {
  "id": "s052",
  "group": "تحذيرية",
  "nameAr": "عمال في الطريق أمامك",
  "nameEn": "Workers in road ahead"
 },
 {
  "id": "s053",
  "group": "تحذيرية",
  "nameAr": "شخص ينظم المرور أمامك",
  "nameEn": "Person directing traffic ahead"
 },
 {
  "id": "s054",
  "group": "تحذيرية",
  "nameAr": "إغلاق مسار",
  "nameEn": "Lane closed"
 },
 {
  "id": "s055",
  "group": "تحذيرية",
  "nameAr": "تحويلة",
  "nameEn": "Detour"
 },
 {
  "id": "s056",
  "group": "تحذيرية",
  "nameAr": "السرعة المقترحة",
  "nameEn": "Suggested speed"
 },
 {
  "id": "s057",
  "group": "تحذيرية",
  "nameAr": "عوائق أمامك (أصفر)",
  "nameEn": "Obstacles ahead (yellow)"
 },
 {
  "id": "s058",
  "group": "تحذيرية",
  "nameAr": "عوائق أمامك (أحمر)",
  "nameEn": "Obstacles ahead (red)"
 },
 {
  "id": "s059",
  "group": "أولوية",
  "nameAr": "أولوية للمركبات القادمة من الجهة المقابلة",
  "nameEn": "Priority to Vehicles Coming from the Opposite Side"
 },
 {
  "id": "s060",
  "group": "أولوية",
  "nameAr": "قف (تصميم 2)",
  "nameEn": "Stop (Type II)"
 },
 {
  "id": "s061",
  "group": "أولوية",
  "nameAr": "قف (بالعربية)",
  "nameEn": "Stop (Arabic)"
 },
 {
  "id": "s062",
  "group": "أولوية",
  "nameAr": "قف (تصميم آخر)",
  "nameEn": "Stop (variant)"
 },
 {
  "id": "s063",
  "group": "أولوية",
  "nameAr": "قف",
  "nameEn": "Stop"
 },
 {
  "id": "s064",
  "group": "أولوية",
  "nameAr": "أعطِ الأولوية",
  "nameEn": "Give way"
 },
 {
  "id": "s065",
  "group": "ممنوعات",
  "nameAr": "الحد الأقصى للسرعة",
  "nameEn": "Maximum speed limit"
 },
 {
  "id": "s066",
  "group": "إلزامية",
  "nameAr": "الشاحنات على اليمين",
  "nameEn": "Trucks keep right"
 },
 {
  "id": "s067",
  "group": "ممنوعات",
  "nameAr": "الحد الأقصى لسرعة الشاحنات",
  "nameEn": "Speed limit for trucks"
 },
 {
  "id": "s068",
  "group": "إلزامية",
  "nameAr": "الحد الأدنى للسرعة",
  "nameEn": "Minimum speed limit"
 },
 {
  "id": "s069",
  "group": "إلزامية",
  "nameAr": "نهاية الحد الأدنى للسرعة",
  "nameEn": "End of minimum speed limit"
 },
 {
  "id": "s070",
  "group": "ممنوعات",
  "nameAr": "ممنوع الدخول",
  "nameEn": "No entry"
 },
 {
  "id": "s071",
  "group": "ممنوعات",
  "nameAr": "ممنوع الدراجات النارية",
  "nameEn": "No motorcycles"
 },
 {
  "id": "s072",
  "group": "ممنوعات",
  "nameAr": "ممنوع الدراجات الهوائية",
  "nameEn": "No bicycles"
 },
 {
  "id": "s073",
  "group": "ممنوعات",
  "nameAr": "ممنوع المركبات ذات المحرك عدا الدراجات النارية",
  "nameEn": "No motor vehicles except motorcycles"
 },
 {
  "id": "s074",
  "group": "ممنوعات",
  "nameAr": "الحد الأقصى لوزن الشاحنات",
  "nameEn": "Maximum weight for trucks"
 },
 {
  "id": "s075",
  "group": "ممنوعات",
  "nameAr": "ممنوع المقطورات",
  "nameEn": "No trailers"
 },
 {
  "id": "s076",
  "group": "ممنوعات",
  "nameAr": "ممنوع المشاة",
  "nameEn": "No pedestrians"
 },
 {
  "id": "s077",
  "group": "ممنوعات",
  "nameAr": "ممنوع العربات التي تجرها الحيوانات",
  "nameEn": "No animal-drawn vehicles"
 },
 {
  "id": "s078",
  "group": "ممنوعات",
  "nameAr": "ممنوع العربات اليدوية",
  "nameEn": "No handcarts"
 },
 {
  "id": "s079",
  "group": "ممنوعات",
  "nameAr": "ممنوع الجرارات",
  "nameEn": "No tractors"
 },
 {
  "id": "s080",
  "group": "ممنوعات",
  "nameAr": "الحد الأقصى للعرض",
  "nameEn": "Maximum width"
 },
 {
  "id": "s081",
  "group": "ممنوعات",
  "nameAr": "الحد الأقصى للارتفاع",
  "nameEn": "Maximum height"
 },
 {
  "id": "s082",
  "group": "ممنوعات",
  "nameAr": "ممنوع المركبات ذات المحرك",
  "nameEn": "No motor vehicles"
 },
 {
  "id": "s083",
  "group": "ممنوعات",
  "nameAr": "ممنوع المركبات ذات المحرك والمجرورة بالحيوانات",
  "nameEn": "No motor vehicles or animal-drawn vehicles"
 },
 {
  "id": "s084",
  "group": "ممنوعات",
  "nameAr": "الحد الأقصى للوزن",
  "nameEn": "Maximum weight"
 },
 {
  "id": "s085",
  "group": "ممنوعات",
  "nameAr": "الحد الأقصى لوزن المحور",
  "nameEn": "Maximum axle weight"
 },
 {
  "id": "s086",
  "group": "ممنوعات",
  "nameAr": "الحد الأقصى للطول",
  "nameEn": "Maximum length"
 },
 {
  "id": "s087",
  "group": "ممنوعات",
  "nameAr": "ممنوع الانعطاف لليسار",
  "nameEn": "No left turn"
 },
 {
  "id": "s088",
  "group": "ممنوعات",
  "nameAr": "ممنوع الانعطاف لليمين",
  "nameEn": "No right turn"
 },
 {
  "id": "s089",
  "group": "ممنوعات",
  "nameAr": "ممنوع الدوران للخلف",
  "nameEn": "No U-turn"
 },
 {
  "id": "s090",
  "group": "ممنوعات",
  "nameAr": "ممنوع التجاوز",
  "nameEn": "No overtaking"
 },
 {
  "id": "s091",
  "group": "ممنوعات",
  "nameAr": "ممنوع تجاوز الشاحنات",
  "nameEn": "No overtaking by trucks"
 },
 {
  "id": "s092",
  "group": "ممنوعات",
  "nameAr": "ممنوع استخدام المنبه",
  "nameEn": "No use of horn"
 },
 {
  "id": "s093",
  "group": "ممنوعات",
  "nameAr": "ممنوع الحافلات",
  "nameEn": "No buses"
 },
 {
  "id": "s094",
  "group": "ممنوعات",
  "nameAr": "نقطة جمارك",
  "nameEn": "Customs post"
 },
 {
  "id": "s095",
  "group": "ممنوعات",
  "nameAr": "أعطِ الأولوية للقادم من الجهة المقابلة",
  "nameEn": "Give way to oncoming traffic"
 },
 {
  "id": "s096",
  "group": "ممنوعات",
  "nameAr": "نهاية جميع القيود",
  "nameEn": "End of all restrictions"
 },
 {
  "id": "s097",
  "group": "ممنوعات",
  "nameAr": "نهاية الحد الأقصى للسرعة",
  "nameEn": "End of maximum speed limit"
 },
 {
  "id": "s098",
  "group": "ممنوعات",
  "nameAr": "نهاية منع التجاوز",
  "nameEn": "End of overtaking prohibition"
 },
 {
  "id": "s099",
  "group": "ممنوعات",
  "nameAr": "نهاية منع تجاوز الشاحنات",
  "nameEn": "End of no overtaking for trucks"
 },
 {
  "id": "s100",
  "group": "ممنوعات",
  "nameAr": "ممنوع الانتظار",
  "nameEn": "No parking"
 },
 {
  "id": "s101",
  "group": "ممنوعات",
  "nameAr": "ممنوع الوقوف والانتظار",
  "nameEn": "No stopping or parking"
 },
 {
  "id": "s102",
  "group": "إلزامية",
  "nameAr": "الزم اليسار",
  "nameEn": "Keep left"
 },
 {
  "id": "s103",
  "group": "إلزامية",
  "nameAr": "الزم اليمين",
  "nameEn": "Keep right"
 },
 {
  "id": "s104",
  "group": "إلزامية",
  "nameAr": "المرور من أي جانب",
  "nameEn": "Pass on either side"
 },
 {
  "id": "s105",
  "group": "إلزامية",
  "nameAr": "انعطف لليسار",
  "nameEn": "Turn left"
 },
 {
  "id": "s106",
  "group": "إلزامية",
  "nameAr": "انعطف لليمين",
  "nameEn": "Turn right"
 },
 {
  "id": "s107",
  "group": "إلزامية",
  "nameAr": "سر للأمام",
  "nameEn": "Go straight"
 },
 {
  "id": "s108",
  "group": "إلزامية",
  "nameAr": "دوران للخلف",
  "nameEn": "U-turn"
 },
 {
  "id": "s109",
  "group": "إلزامية",
  "nameAr": "دوران للخلف أو للأمام",
  "nameEn": "U-turn or straight ahead"
 },
 {
  "id": "s110",
  "group": "إلزامية",
  "nameAr": "انعطاف لليسار أو لليمين",
  "nameEn": "Turn left or right"
 },
 {
  "id": "s111",
  "group": "إلزامية",
  "nameAr": "انعطاف لليسار أمامك",
  "nameEn": "Turn left ahead"
 },
 {
  "id": "s112",
  "group": "إلزامية",
  "nameAr": "انعطاف لليمين أمامك",
  "nameEn": "Turn right ahead"
 },
 {
  "id": "s113",
  "group": "إلزامية",
  "nameAr": "للأمام أو لليسار",
  "nameEn": "Go straight or turn left"
 },
 {
  "id": "s114",
  "group": "إلزامية",
  "nameAr": "للأمام أو لليمين",
  "nameEn": "Go straight or turn right"
 },
 {
  "id": "s115",
  "group": "إلزامية",
  "nameAr": "دوار",
  "nameEn": "Roundabout"
 },
 {
  "id": "s116",
  "group": "إلزامية",
  "nameAr": "للدراجات الهوائية فقط",
  "nameEn": "Cyclists only"
 },
 {
  "id": "s117",
  "group": "إلزامية",
  "nameAr": "للمشاة فقط",
  "nameEn": "Pedestrians only"
 },
 {
  "id": "s118",
  "group": "إلزامية",
  "nameAr": "مسار الخيول",
  "nameEn": "Equestrian path"
 },
 {
  "id": "s119",
  "group": "ممنوعات",
  "nameAr": "ممنوع الانعطاف لليمين (تصميم آخر)",
  "nameEn": "No right turn (variant)"
 },
 {
  "id": "s120",
  "group": "ممنوعات",
  "nameAr": "السرعة القصوى 120",
  "nameEn": "Speed limit 120"
 },
 {
  "id": "s121",
  "group": "ممنوعات",
  "nameAr": "السرعة القصوى 125",
  "nameEn": "Speed limit 125"
 },
 {
  "id": "s122",
  "group": "إرشادية",
  "nameAr": "لوحة طريق سريع",
  "nameEn": "Highway sign"
 },
 {
  "id": "s123",
  "group": "إرشادية",
  "nameAr": "لوحة طريق داخل المدينة",
  "nameEn": "City road sign"
 },
 {
  "id": "s124",
  "group": "إرشادية",
  "nameAr": "لوحة اتجاه مكة المكرمة",
  "nameEn": "Makkah direction sign"
 },
 {
  "id": "s125",
  "group": "إرشادية",
  "nameAr": "لوحة طريق فرعي",
  "nameEn": "Side road sign"
 },
 {
  "id": "s126",
  "group": "إرشادية",
  "nameAr": "اتجاه الشمال",
  "nameEn": "North sign"
 },
 {
  "id": "s127",
  "group": "إرشادية",
  "nameAr": "اتجاه الشرق",
  "nameEn": "East sign"
 },
 {
  "id": "s128",
  "group": "إرشادية",
  "nameAr": "اتجاه الجنوب",
  "nameEn": "South sign"
 },
 {
  "id": "s129",
  "group": "إرشادية",
  "nameAr": "اتجاه الغرب",
  "nameEn": "West sign"
 },
 {
  "id": "s130",
  "group": "إرشادية",
  "nameAr": "طريق مسدود",
  "nameEn": "Dead end"
 },
 {
  "id": "s131",
  "group": "إرشادية",
  "nameAr": "شغّل الأضواء",
  "nameEn": "Turn on lights"
 },
 {
  "id": "s132",
  "group": "إرشادية",
  "nameAr": "مستشفى",
  "nameEn": "Hospital"
 },
 {
  "id": "s133",
  "group": "إرشادية",
  "nameAr": "إسعافات أولية",
  "nameEn": "First aid"
 },
 {
  "id": "s134",
  "group": "إرشادية",
  "nameAr": "فندق",
  "nameEn": "Hotel"
 },
 {
  "id": "s135",
  "group": "إرشادية",
  "nameAr": "مطعم",
  "nameEn": "Restaurant"
 },
 {
  "id": "s136",
  "group": "إرشادية",
  "nameAr": "مقهى",
  "nameEn": "Cafe"
 },
 {
  "id": "s137",
  "group": "إرشادية",
  "nameAr": "محطة وقود",
  "nameEn": "Fuel station"
 },
 {
  "id": "s138",
  "group": "إرشادية",
  "nameAr": "خدمة إصلاح الأعطال",
  "nameEn": "Breakdown service"
 },
 {
  "id": "s139",
  "group": "إرشادية",
  "nameAr": "هاتف",
  "nameEn": "Telephone"
 },
 {
  "id": "s140",
  "group": "إرشادية",
  "nameAr": "حديقة",
  "nameEn": "Park"
 },
 {
  "id": "s141",
  "group": "إرشادية",
  "nameAr": "تخييم",
  "nameEn": "Camping"
 },
 {
  "id": "s142",
  "group": "إرشادية",
  "nameAr": "موقف سيارات",
  "nameEn": "Parking"
 },
 {
  "id": "s143",
  "group": "إرشادية",
  "nameAr": "اتجاه المواقف",
  "nameEn": "Direction to parking"
 },
 {
  "id": "s144",
  "group": "إرشادية",
  "nameAr": "معبر مشاة",
  "nameEn": "Pedestrian crossing"
 },
 {
  "id": "s145",
  "group": "إرشادية",
  "nameAr": "طريق سريع",
  "nameEn": "Expressway"
 },
 {
  "id": "s146",
  "group": "إرشادية",
  "nameAr": "نهاية الطريق السريع",
  "nameEn": "End of expressway"
 },
 {
  "id": "s147",
  "group": "إرشادية",
  "nameAr": "وسط المدينة",
  "nameEn": "City centre"
 },
 {
  "id": "s148",
  "group": "إرشادية",
  "nameAr": "اسم الشارع",
  "nameEn": "Street name"
 },
 {
  "id": "s149",
  "group": "إرشادية",
  "nameAr": "متاحف ومراكز ترفيه ومزارع",
  "nameEn": "Museums, entertainment centres and farms"
 },
 {
  "id": "s150",
  "group": "إرشادية",
  "nameAr": "لوحة اتجاهات",
  "nameEn": "Directional sign"
 },
 {
  "id": "s151",
  "group": "إرشادية",
  "nameAr": "لوحة اتجاهات (تصميم 2)",
  "nameEn": "Directional sign (Type II)"
 },
 {
  "id": "s152",
  "group": "إرشادية",
  "nameAr": "وسط المدينة (تصميم 2)",
  "nameEn": "City centre (Type II)"
 },
 {
  "id": "s153",
  "group": "إرشادية",
  "nameAr": "اتجاه الشرق (تصميم 1)",
  "nameEn": "East sign (Type I)"
 },
 {
  "id": "s154",
  "group": "إرشادية",
  "nameAr": "اتجاه الشمال (تصميم 1)",
  "nameEn": "North sign (Type I)"
 },
 {
  "id": "s155",
  "group": "إرشادية",
  "nameAr": "اتجاه الجنوب (تصميم 1)",
  "nameEn": "South sign (Type I)"
 },
 {
  "id": "s156",
  "group": "إرشادية",
  "nameAr": "اتجاه الغرب (تصميم 1)",
  "nameEn": "West sign (Type I)"
 },
 {
  "id": "s157",
  "group": "لوحات الطرق",
  "nameAr": "لوحة طريق فرعي فارغة",
  "nameEn": "Side road sign (blank)"
 },
 {
  "id": "s158",
  "group": "لوحات الطرق",
  "nameAr": "لوحة طريق فرعي",
  "nameEn": "Side road sign"
 },
 {
  "id": "s159",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة فارغة",
  "nameEn": "City sign (blank)"
 },
 {
  "id": "s160",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s161",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s162",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s163",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s164",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s165",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s166",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s167",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s168",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s169",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s170",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s171",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s172",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s173",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s174",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s175",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s176",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s177",
  "group": "لوحات الطرق",
  "nameAr": "لوحة مدينة",
  "nameEn": "City sign"
 },
 {
  "id": "s178",
  "group": "لوحات الطرق",
  "nameAr": "لوحة طريق سريع فارغة",
  "nameEn": "Highway sign (blank)"
 },
 {
  "id": "s179",
  "group": "لوحات الطرق",
  "nameAr": "طريق سريع رقم 10",
  "nameEn": "Highway 10"
 },
 {
  "id": "s180",
  "group": "لوحات الطرق",
  "nameAr": "طريق سريع رقم 15",
  "nameEn": "Highway 15"
 },
 {
  "id": "s181",
  "group": "لوحات الطرق",
  "nameAr": "طريق سريع رقم 2",
  "nameEn": "Highway 2"
 },
 {
  "id": "s182",
  "group": "لوحات الطرق",
  "nameAr": "طريق سريع رقم 30",
  "nameEn": "Highway 30"
 },
 {
  "id": "s183",
  "group": "لوحات الطرق",
  "nameAr": "طريق سريع رقم 5",
  "nameEn": "Highway 5"
 },
 {
  "id": "s184",
  "group": "لوحات الطرق",
  "nameAr": "طريق سريع رقم 50",
  "nameEn": "Highway 50"
 },
 {
  "id": "s185",
  "group": "لوحات الطرق",
  "nameAr": "طريق سريع رقم 60",
  "nameEn": "Highway 60"
 },
 {
  "id": "s186",
  "group": "لوحات الطرق",
  "nameAr": "طريق سريع رقم 65",
  "nameEn": "Highway 65"
 },
 {
  "id": "s187",
  "group": "لوحات الطرق",
  "nameAr": "طريق سريع رقم 70",
  "nameEn": "Highway 70"
 },
 {
  "id": "s188",
  "group": "لوحات الطرق",
  "nameAr": "طريق سريع رقم 75",
  "nameEn": "Highway 75"
 },
 {
  "id": "s189",
  "group": "لوحات الطرق",
  "nameAr": "طريق سريع رقم 80",
  "nameEn": "Highway 80"
 },
 {
  "id": "s190",
  "group": "لوحات الطرق",
  "nameAr": "طريق سريع رقم 85",
  "nameEn": "Highway 85"
 },
 {
  "id": "s191",
  "group": "لوحات الطرق",
  "nameAr": "طريق سريع رقم 95",
  "nameEn": "Highway 95"
 }
];
