// Generated by scripts/extract.py from the web app. Do not edit by hand.
import type { Lang, Step } from './types';

/** Compiled from public service pages (general information, not official). Verify on Absher. */
export const STEPS_SOURCE = 'general' as const;

export const STEPS: Record<Lang, Step[]> = {
 "ar": [
  {
   "title": "الشروط",
   "body": "العمر 18 سنة للرخصة الخاصة (توجد إجراءات تصريح قيادة مؤقت من عمر 17، تحقق منها عبر أبشر)."
  },
  {
   "title": "الفحص الطبي",
   "body": "إجراء الفحص الطبي (يشمل النظر والفحص العام) في أحد المراكز المعتمدة."
  },
  {
   "title": "حجز موعد عبر أبشر",
   "body": "أبشر أفراد ← مواعيد ← المرور ← «تدريب في مدارس القيادة»، ثم اختر المنطقة والمدرسة والموعد."
  },
  {
   "title": "التقييم والتسجيل في المدرسة",
   "body": "يحدد التقييم مسارك وعدد ساعات التدريب (للمبتدئ غالباً بين 22 و30 ساعة). تختلف رسوم التدريب بحسب المدرسة والمسار وقد تصل إلى نحو 2760 ريالاً."
  },
  {
   "title": "التدريب والاختبارات",
   "body": "حضور الحصص النظرية والعملية، ثم اختبار الحاسب الآلي (النظري) والاختبار العملي. رسوم إعادة الاختبار عند الرسوب: 10 ريالات."
  },
  {
   "title": "سداد رسوم الرخصة واستلامها",
   "body": "سنتان: 85 ريالاً · 5 سنوات: 200 ريال · 10 سنوات: 400 ريال. تصدر الرخصة بعد سداد الرسوم وتسوية أي مخالفات."
  }
 ],
 "en": [
  {
   "title": "Eligibility",
   "body": "Age 18+ for a private license (a temporary permit may be available from 17; check Absher)."
  },
  {
   "title": "Medical check",
   "body": "Complete the medical check (including vision) at an approved center."
  },
  {
   "title": "Book on Absher",
   "body": "Absher Individuals → Appointments → Traffic → “Training at driving schools”, then choose region, school and time."
  },
  {
   "title": "Assessment and registration",
   "body": "The school assesses your level and sets your track and hours (usually 22–30 hours for beginners). Training fees vary by school and track, up to about SAR 2,760."
  },
  {
   "title": "Training and tests",
   "body": "Attend theory and practical sessions, then take the computer (theory) test and the road test. Retake fee after a fail: SAR 10."
  },
  {
   "title": "Pay and receive",
   "body": "Fees: 2 years SAR 85 · 5 years SAR 200 · 10 years SAR 400. The license is issued after payment and clearing any fines."
  }
 ],
 "ur": [
  {
   "title": "اہلیت",
   "body": "نجی لائسنس کے لیے عمر 18 سال یا زیادہ (17 سال سے عارضی اجازت نامہ ممکن ہے، ابشر پر دیکھیں)۔"
  },
  {
   "title": "طبی معائنہ",
   "body": "منظور شدہ مرکز سے طبی معائنہ (بینائی سمیت) کروائیں۔"
  },
  {
   "title": "ابشر پر بکنگ",
   "body": "ابشر افراد ← اپائنٹمنٹس ← ٹریفک ← «ڈرائیونگ اسکولوں میں تربیت»، پھر علاقہ، اسکول اور وقت منتخب کریں۔"
  },
  {
   "title": "جائزہ اور اندراج",
   "body": "اسکول آپ کی سطح کا جائزہ لے کر ٹریک اور گھنٹے طے کرتا ہے (نئے سیکھنے والوں کے لیے عموماً 22 سے 30 گھنٹے)۔ فیس اسکول اور ٹریک کے مطابق مختلف ہے، تقریباً 2760 ریال تک۔"
  },
  {
   "title": "تربیت اور امتحانات",
   "body": "نظری اور عملی کلاسیں، پھر کمپیوٹر (نظری) امتحان اور عملی امتحان۔ فیل ہونے پر دوبارہ امتحان کی فیس 10 ریال۔"
  },
  {
   "title": "فیس اور وصولی",
   "body": "لائسنس فیس: 2 سال 85 ریال · 5 سال 200 ریال · 10 سال 400 ریال۔ فیس ادا کرنے اور چالان کلیئر ہونے کے بعد لائسنس جاری ہوتا ہے۔"
  }
 ]
};
