// Generated by scripts/extract.py from the web app. Do not edit by hand.
import type { Lang, Tip } from './types';

/** Quick tips summarised from the official trainee guide. */
export const TIPS: Record<Lang, Tip[]> = {
 "ar": [
  {
   "title": "قاعدة الثانيتين",
   "lines": [
    "اختر نقطة ثابتة على الطريق، وعندما تمر المركبة التي أمامك عندها ابدأ العد: «ألف وواحد، ألف واثنان».",
    "إذا وصلت النقطة قبل انتهاء العد فأنت قريب جداً، زد المسافة.",
    "زد المسافة في الطرق المبللة والرمال، وعند القيادة خلف الدراجات النارية أو المركبات المحملة."
   ]
  },
  {
   "title": "مسافة التوقف",
   "lines": [
    "مسافة التوقف = مسافة ردة الفعل + مسافة الفرملة.",
    "مسافة ردة الفعل = (السرعة ÷ 10) × 3",
    "مسافة الفرملة = (السرعة ÷ 10) × (السرعة ÷ 10)",
    "مثال: عند 50 كم/س → 15 + 25 = 40 متراً تقريباً."
   ]
  },
  {
   "title": "حدود السرعة العامة",
   "lines": [
    "المركبات الصغيرة: 80 كم/س داخل المدينة، و120 كم/س خارجها.",
    "المركبات الكبيرة داخل المدينة: 50 كم/س.",
    "خفف السرعة عند الضباب والمطر والعواصف الرملية وتدني الرؤية."
   ]
  },
  {
   "title": "قبل أن تقود",
   "lines": [
    "افحص النوافذ والأضواء والمرايا والإطارات.",
    "اربط حزام الأمان، وضع الأطفال دون 12 سنة في المقاعد المخصصة لهم.",
    "لا تقد وأنت مرهق أو مريض أو مشتت، وانتبه لتأثير الأدوية على القيادة."
   ]
  },
  {
   "title": "تغيير المسار والتجاوز",
   "lines": [
    "الترتيب: المرايا ← الإشارة ← النظر إلى الكتف (النقطة العمياء) ← ضبط السرعة ← التحرك بسلاسة.",
    "التجاوز يكون عادةً من اليسار، ويمنع عند التقاطعات والمنحنيات وقمم التلال والجسور وعند تدني الرؤية."
   ]
  },
  {
   "title": "الأولوية والدوار",
   "lines": [
    "عند وصول مركبتين للتقاطع في نفس الوقت فالأولوية للتي على الجانب الأيمن.",
    "داخل الدوار الأولوية للمركبات التي فيه، ويُعطى الإشارة لليمين قبل المخرج."
   ]
  },
  {
   "title": "عند الحوادث والطوارئ",
   "lines": [
    "أوقف المركبة، أمّن المكان، قدّم المساعدة الممكنة وأبلغ الجهات المختصة.",
    "أفسح الطريق لمركبات الطوارئ ولا تقد خلفها بمسافة تقل عن 50 متراً."
   ]
  }
 ],
 "en": [
  {
   "title": "Two-second rule",
   "lines": [
    "Pick a fixed point on the road. When the car ahead passes it, count “one-thousand-one, one-thousand-two”.",
    "If you reach the point before the count ends, you are too close: increase the gap.",
    "Leave more space on wet roads and sand, and behind motorcycles or heavily loaded vehicles."
   ]
  },
  {
   "title": "Stopping distance",
   "lines": [
    "Stopping distance = reaction distance + braking distance.",
    "Reaction distance = (speed ÷ 10) × 3",
    "Braking distance = (speed ÷ 10) × (speed ÷ 10)",
    "Example: at 50 km/h → 15 + 25 = about 40 m."
   ]
  },
  {
   "title": "General speed limits",
   "lines": [
    "Small vehicles: 80 km/h in cities and 120 km/h outside.",
    "Large vehicles in cities: 50 km/h.",
    "Slow down in fog, rain, sandstorms and poor visibility."
   ]
  },
  {
   "title": "Before you drive",
   "lines": [
    "Check windows, lights, mirrors and tyres.",
    "Fasten your seat belt; children under 12 must use a suitable child seat.",
    "Do not drive tired, ill or distracted, and read medicine warnings."
   ]
  },
  {
   "title": "Lane changes and overtaking",
   "lines": [
    "Order: mirrors → signal → shoulder check (blind spot) → adjust speed → move smoothly.",
    "Overtake normally on the left; never at junctions, bends, hill crests, bridges or in poor visibility."
   ]
  },
  {
   "title": "Priority and roundabouts",
   "lines": [
    "If two vehicles reach a junction together, the one on the right goes first.",
    "In a roundabout, vehicles already inside have priority; signal right before your exit."
   ]
  },
  {
   "title": "Accidents and emergencies",
   "lines": [
    "Stop, secure the scene, help where possible and report to the authorities.",
    "Give way to emergency vehicles and keep at least 50 m behind them."
   ]
  }
 ],
 "ur": [
  {
   "title": "دو سیکنڈ کا اصول",
   "lines": [
    "سڑک پر کوئی مقررہ نقطہ چنیں۔ آگے والی گاڑی وہاں سے گزرے تو گنیں: «ایک ہزار ایک، ایک ہزار دو»۔",
    "اگر گنتی مکمل ہونے سے پہلے آپ اس نقطے پر پہنچ جائیں تو فاصلہ کم ہے، اسے بڑھائیں۔",
    "گیلی سڑک، ریت، موٹر سائیکل یا بھاری لدی گاڑی کے پیچھے فاصلہ زیادہ رکھیں۔"
   ]
  },
  {
   "title": "رکنے کا فاصلہ",
   "lines": [
    "رکنے کا فاصلہ = ردعمل کا فاصلہ + بریک کا فاصلہ۔",
    "ردعمل کا فاصلہ = (رفتار ÷ 10) × 3",
    "بریک کا فاصلہ = (رفتار ÷ 10) × (رفتار ÷ 10)",
    "مثال: 50 کلومیٹر فی گھنٹہ پر ← 15 + 25 = تقریباً 40 میٹر۔"
   ]
  },
  {
   "title": "رفتار کی عمومی حدیں",
   "lines": [
    "چھوٹی گاڑیاں: شہر میں 80 اور شہر سے باہر 120 کلومیٹر فی گھنٹہ۔",
    "بڑی گاڑیاں شہر میں: 50 کلومیٹر فی گھنٹہ۔",
    "دھند، بارش، ریتلی آندھی اور کم نظر آنے کی صورت میں رفتار کم کریں۔"
   ]
  },
  {
   "title": "گاڑی چلانے سے پہلے",
   "lines": [
    "کھڑکیاں، لائٹیں، آئینے اور ٹائر چیک کریں۔",
    "سیٹ بیلٹ باندھیں؛ 12 سال سے کم بچے مناسب چائلڈ سیٹ میں ہوں۔",
    "تھکاوٹ، بیماری یا توجہ ہٹنے کی حالت میں گاڑی نہ چلائیں اور دوا کی ہدایات پڑھیں۔"
   ]
  },
  {
   "title": "لین بدلنا اور اوورٹیک",
   "lines": [
    "ترتیب: آئینے ← اشارہ ← کندھے کے اوپر سے دیکھنا ← رفتار ← نرمی سے حرکت۔",
    "اوورٹیک عموماً بائیں سے کریں؛ چوراہوں، موڑ، ڈھلوان کی چوٹی، پلوں اور کم نظر آنے پر منع ہے۔"
   ]
  },
  {
   "title": "ترجیح اور راؤنڈ اباؤٹ",
   "lines": [
    "دو گاڑیاں ایک ساتھ چوراہے پر پہنچیں تو دائیں جانب والی پہلے جائے۔",
    "راؤنڈ اباؤٹ میں اندر موجود گاڑیوں کو ترجیح ہے؛ اپنے اخراج سے پہلے دایاں اشارہ دیں۔"
   ]
  },
  {
   "title": "حادثات اور ہنگامی حالات",
   "lines": [
    "رکیں، جگہ محفوظ کریں، ممکنہ مدد کریں اور متعلقہ اداروں کو اطلاع دیں۔",
    "ایمرجنسی گاڑیوں کو راستہ دیں اور ان کے پیچھے کم از کم 50 میٹر فاصلہ رکھیں۔"
   ]
  }
 ]
};

export const TIRE_RATINGS: [string, number][] = [["L", 120], ["M", 130], ["N", 140], ["P", 150], ["Q", 160], ["R", 170], ["S", 180], ["T", 190], ["U", 200], ["H", 210], ["V", 240], ["W", 270], ["Y", 300]];
